data = {
    "completes any math required as part of the team's assignments": [0, 3],
    'performs more effectively than any other team member': [0, 5],
    'completes all assigned tasks on time': [0, 3],
    'effectively completes tasks, no matter what': [0, 5],
    'adds ideas to projects that make the work better': [0, 5],
    'does an equal share of the work': [0, 3],
    'identifies solutions for issues that no one else is able to address': [0, 5],
    'completes the tasks needed': [0, 3],
    'comes up with important ideas during team brainstorming': [0, 5],
    'engages in little taskwork if not pushed by others': [0, 1],
    'consistently meets the expectations of the assignment': [0, 3],
    'provides valuable input for accomplishing team assignments': [0, 5],
    'sits idly in team meetings': [0, 1],
    'adds input to the team assignments': [0, 3],
    'always volunteers to perform additional work as needed': [0, 5],
    'shows up late, if at all, to team meetings': [0, 1],
    'does more work than what is needed': [0, 5],
    'always offers ideas about how to complete tasks, no matter what the task is': [0, 5],
    "fails to complete personal taskwork required for the team's assignment": [0, 2],
    'does fair share of the work, but generally not above and beyond the fair share': [0, 3],
    'turns in acceptable, but not outstanding, work': [0, 3],
    'puts in more effort than any other member of the team': [0, 5],
    'generates ideas that help the team': [0, 5],
    "generates new ideas to improve the team's assignment that the rest of the team had not thought of": [0, 5],
    'never reads the material prior to meeting': [0, 1],
    'frequently misses team meetings': [0, 1],
    'submits work that fails to meet the task requirements explicitly stated by the team': [0, 1],
    'routinely late to team meetings': [0, 1],
    'performs a significant amount of work on assignments': [0, 5],
    'adds little, if anything, to team assignments': [0, 1],
    "actively listens to others' opinions and ideas of how things should be done": [1, 3],
    "seeks input from team members that haven't voiced ideas yet": [1, 5],
    'redirects negative comments of other team members to keep things positive': [1, 5],
    'shares ideas openly with fellow team members': [1, 3],
    'is often combative when own ideas are not adopted': [1, 1],
    "respects other team members' opinions": [1, 3],
    'communicates well with the other team members': [1, 4],
    "asks everyone to contribute ideas so everyone's voice is heard during team meetings": [1, 5],
    'involves everyone in discussions': [1, 5],
    "listens to everyone's opinions": [1, 3],
    "often encourages teammates' thoughts and opinions": [1, 5],
    'listens to everyone': [1, 3],
    'frequently absent': [1, 1],
    'displays nonverbal signs of frustration, disinterest, or contempt towards working with others on the team': [1, 1],
    "closed-minded regarding others' ideas": [1, 1],
    'displays a negative attitude towards anything that the team does': [1, 1],
    'fails to give status reports to other team members': [1, 1],
    'boosts team morale by complimenting members on their work': [1, 5],
    'cheers on teammates': [1, 5],
    'often argues with other teammates': [1, 1],
    'disregards abstract and creative ideas from other team members': [1, 1],
    "ignores other team members' ideas and opinions": [1, 1],
    "stubbornly disagrees with the team's decisions if not aligned with own ideas": [1, 1],
    'often coordinates meetings when others forget': [2, 5],
    'encourages the team members to stay on the tasks': [2, 3],
    'finds a way to get the team back on track regardless of what else is occurring': [2, 5],
    'helps the team think of issues that have been overlooked': [2, 3],
    'reminds team of deadlines to help encourage the completion of tasks': [2, 3],
    'appropriately assigns roles to team members to get the most productivity out of everyone': [2, 5],
    'sets goals and checkpoints to help the team': [2, 5],
    "identifies weaknesses in the team's developments": [2, 3],
    'does not give feedback on a problem unless someone else addresses a concern first': [2, 1],
    'sets internal deadlines to push the team to complete goals effectively': [2, 5],
    'records team progress and tasks remaining': [2, 3],
    'rarely checks on progress of other team members': [2, 1],
    'creates goals to help the team monitor its progress': [2, 5],
    'gives constructive feedback': [2, 5],
    'takes the initiative to make sure everyone makes it to the meetings and gets their work done': [2, 5],
    'keeps track of deadlines and holds team members to those deadlines to ensure the project is completed in the time allotted': [2, 5],
    'writes down a checklist of what the team needs to get done for meetings': [2, 5],
    'does not follow up with team members about tasking to ensure understanding': [2, 1],
    'does not mention problems right away, but later comments about having noticed those issues': [2, 1],
    'provides irrelevant information that further confuses the team when the team is attempting to overcome a problem': [2, 1],
    'ensures that things get done by asking if each member understands the tasks that they need to accomplish': [2, 3],
    'organizes team meetings': [2, 5],
    'distracts the other team members by talking about topics that have nothing to do with the task': [2, 1],
    'writes checklists that keep the team focused': [2, 5],
    'reviews all work before submitting it to the team to ensure it is of top quality': [3, 5],
    'encourages team to check work for errors': [3, 3],
    'encourages the team to achieve its highest potential': [3, 5],
    'usually reads and double-checks the work before submitting it': [3, 3],
    'talks about the need to get good grades by turning in quality work': [3, 3],
    'communicates high expectations with regard to the quality of assignments': [3, 5],
    'ignores errors in the work and suggests that it is ok to submit as is without fixing errors': [3, 1],
    'makes statements indicating a greater concern for just getting done rather than ensuring a quality job': [3, 1],
    'often makes statements implying the team will fail the assignment': [3, 1],
    'encourages the team to do better than it normally would': [3, 5],
    'finishes work as quickly as possible without regard for whether it is done correctly': [3, 1],
    'invests time to ensure the team is doing the job well': [3, 3],
    'questions things to ensure that processes are the best they can be': [3, 5],
    'checks work to ensure it is generally correct': [3, 3],
    "shows little concern about the team's performance on assignments": [3, 1],
    'learned computer skills required for the assignment so the team could complete the task': [4, 5],
    'figures out how to do the math for assigned problems': [4, 3],
    'shows skills in areas where the rest of the team does not have them': [4, 5],
    'uses computer skills to help solve some problems': [4, 3],
    'able to use base knowledge of computers in some assignments': [4, 3],
    "relies upon an excellent knowledge base that greatly assists in solving the team's problems": [4, 5],
    'uses relevant math skills': [4, 3],
    'accomplishes tasks quickly by using extensive knowledge base': [4, 5],
    'does not try to learn the skills needed to complete the task': [4, 1],
    'expresses frustration when trying to complete tasks that require task-specific knowledge and skills': [4, 1],
    'completes the required mathematical operations due to having the expected mathematical skills for this course': [4, 3],
    'applies previous knowledge of computer programs to tasks': [4, 3],
    'applies previously gained programming knowledge to complete tasks': [4, 3],
    'able to contribute to all assignments because of an unusually strong understanding of the required mathematical knowledge and skills': [4, 5],
    'relies on extensive computer skills to complete team assignments': [4, 5],
    'demonstrates outstanding mathematics skills': [4, 5],
    'unable to complete basic tasks because he/she is struggling to understand the material': [4, 1]
};